name: vm_snapshot_analysis
description: Utilities for analysing AOT snapshot size.
version: 0.6.0

homepage: https://github.com/dart-lang/sdk/tree/master/pkg/vm_snapshot_analysis

environment:
  sdk: '>=2.8.0 <3.0.0'

executables:
  snapshot_analysis: analyse

dependencies:
  args: ^2.0.0
  path: ^1.8.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
