name: analyzer
version: 0.42.0
description: This package provides a library that performs static analysis of Dart code.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/analyzer

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  _fe_analyzer_shared: ^14.0.0
  args: ^2.0.0-nullsafety.0
  cli_util: ^0.3.0-nullsafety.0
  collection: ^1.15.0-nullsafety.5
  convert: ^3.0.0-nullsafety.0
  crypto: ^3.0.0-nullsafety.0
  glob: ^2.0.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6
  package_config: ^2.0.0-nullsafety.0
  path: ^1.8.0-nullsafety.3
  pub_semver: ^2.0.0-nullsafety.0
  source_span: ^1.8.0-nullsafety.4
  watcher: ^1.0.0-nullsafety.0
  yaml: ^3.0.0-nullsafety.0
dev_dependencies:
  analyzer_utilities:
    path: ../analyzer_utilities
  async: ^2.5.0-nullsafety.3
#  linter: any
  matcher: ^0.12.10-nullsafety.3
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
  test_api: ^0.2.19-nullsafety.6
  test_reflective_loader: ^0.2.0-nullsafety.0
